[package]
name = "make"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
index.workspace = true
data.workspace = true
walkdir.workspace = true
minify-html.workspace = true
starrailrust.workspace = true
icon.workspace = true